export const APP_CONFIG = {
    BACKEND_DOMAIN: 'https://619b146827827600174453b2.mockapi.io',
    BACKEND_API_END_POINT: 'api',
    BACKEND_API_VERSION: 'v1',
  };
export const BACKEND_URL = `${APP_CONFIG.BACKEND_DOMAIN}/${APP_CONFIG.BACKEND_API_END_POINT}/${APP_CONFIG.BACKEND_API_VERSION}`