export const LOADING_REQUEST = 'LOADING_REQUEST';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';

export const TODO_REQUEST = 'TODO_REQUEST'
export const TODO_SUCCESS = 'TODO_SUCCESS'
export const TODO_ERROR = 'TODO_ERROR'

export const THUNKTODO_REQUEST = "THUNKTODO_REQUEST"
export const THUNKTODO_SUCCESS = "THUNKTODO_SUCCESS"
export const THUNKTODO_ERROR = "THUNKTODO_ERROR"